apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ns.yaml
  - data-simulator-scc-rbac.yaml
  - mysql.yaml
  - datasimulator-deployment.yaml
  - cloudbeaver.yaml
