kind: Secret
apiVersion: v1
metadata:
  name: htpasswd-pass
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "0"
data:
  htpasswd: REPLACEME-WITH-YOUR-HTPASSWD
type: Opaque
