apiVersion: v1
kind: Secret
metadata:
  name: spark-s3-credentials
  namespace: spark-history-server
  labels:
    app: spark-history-server
    component: spark
type: Opaque
stringData:
  s3-endpoint: "http://minio-service.minio.svc.cluster.local:9000"
  s3-access-key: "minio"
  s3-secret-key: "minio123"
