# Enterprise Gateway for Kubeflow Notebooks + Spark Operator
# Ref: https://www.kubeflow.org/docs/components/spark-operator/user-guide/notebooks-spark-operator/

global:
  rbac: true

image: elyra/enterprise-gateway:3.2.3
imagePullPolicy: Always
logLevel: DEBUG

kernel:
  shareGatewayNamespace: true
  launchTimeout: 300
  cullIdleTimeout: 3600
  allowedKernels:
    - spark_python_operator
    - python3
  defaultKernelName: spark_python_operator

kernelspecsPvc:
  enabled: true
  name: pvc-kernelspecs

deployment:
  enabled: true
  securityContext:
    runAsUser: 0
    runAsGroup: 0

kip:
  enabled: false
  image: elyra/kernel-image-puller:3.2.3
  imagePullPolicy: Always
  pullPolicy: Always
  defaultContainerRegistry: quay.io
