apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  creationTimestamp: "2026-02-17T23:56:07Z"
  finalizers:
  - datasciencepipelinesapplications.opendatahub.io/finalizer
  generation: 2
  name: dspa
  namespace: spark-etl-project
  resourceVersion: "1613362"
  uid: ca39ec3f-124f-4ed9-b484-80a6d2caeea4
spec:
  apiServer:
    artifactSignedURLExpirySeconds: 60
    caBundleFileMountPath: ""
    caBundleFileName: ""
    cacheEnabled: true
    deploy: true
    enableOauth: true
    enableSamplePipeline: false
    managedPipelines:
      instructLab:
        state: Removed
    pipelineStore: kubernetes
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:
      basePath: ""
      bucket: spark-etl-pipeline
      host: minio-service.minio.svc.cluster.local:9000
      port: ""
      region: us-east-1
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: dashboard-dspa-secret
      scheme: http
  persistenceAgent:
    deploy: true
    numWorkers: 2
  podToPodTLS: true
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
