apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: spark-etl-project
    openshift.io/requester: mabe
    openshift.io/sa.scc.mcs: s0:c30,c25
    openshift.io/sa.scc.supplemental-groups: 1000920000/10000
    openshift.io/sa.scc.uid-range: 1000920000/10000
  creationTimestamp: "2026-02-17T23:14:09Z"
  labels:
    kubernetes.io/metadata.name: spark-etl-project
    opendatahub.io/dashboard: "true"
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  name: spark-etl-project
  resourceVersion: "1581278"
  uid: c0c3e649-1139-4221-8e2b-1323c69eca5f
spec:
  finalizers:
  - kubernetes
status:
  phase: Active