apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-etl
  namespace: spark-etl-project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: spark-etl-project
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - services
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: spark-etl-project
subjects:
- kind: ServiceAccount
  name: spark-etl
  namespace: spark-etl-project
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
