{
 "title": "Spark Applications Dashboard",
 "description": "Spark Executors and Driver Level Metrics with filtering by service",
 "tags": [ "spark" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Drivers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_labels{namespace=~\"$namespace\", label_spark_role=\"driver\"})"
    }
   ]
  },
  {
   "title": "CPUs Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=~\"spark-kubernetes-driver\", resource=\"cpu\"})",
     "legendFormat": "CPUs Used by Driver"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=~\"spark-kubernetes-executor\", resource=\"cpu\"})",
     "legendFormat": "CPUs Used by Executor"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=~\"spark-kubernetes-driver|spark-kubernetes-executor\", resource=\"cpu\"})",
     "legendFormat": "Total CPUs Used"
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=~\"spark-kubernetes-driver\", resource=\"memory\"})",
     "legendFormat": "Mem Used by Driver"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=~\"spark-kubernetes-executor\", resource=\"memory\"})",
     "legendFormat": "Mem Used by Executors"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=~\"spark-kubernetes-driver|spark-kubernetes-executor\", resource=\"memory\"})",
     "legendFormat": "Total Mem Used"
    }
   ]
  },
  {
   "title": "Executors Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_labels{namespace=~\"$namespace\", label_spark_role=\"executor\"})"
    }
   ]
  },
  { "title": "Execution Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Driver Heap (max/used)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{namespace=~\"$namespace\", area=\"heap\", pod=~\".*driver.*\"}",
     "legendFormat": "Heap max ({{pod}})"
    },
    {
     "expr": "jvm_memory_bytes_used{namespace=~\"$namespace\", area=\"heap\", pod=~\".*driver.*\"}",
     "legendFormat": "Heap used ({{pod}})"
    }
   ]
  },
  {
   "title": "Executor Heap (max/used)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "spark_executor_jvm_total_max_type_gauges{app_namespace=~\"$namespace\"}",
     "legendFormat": "Heap max ({{app_id}}/{{executor_id}})"
    },
    {
     "expr": "spark_executor_jvm_total_used_type_gauges{app_namespace=~\"$namespace\"}",
     "legendFormat": "Heap used ({{app_id}}/{{executor_id}})"
    }
   ]
  },
  {
   "title": "Driver JVM heap by pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\", pod=~\".*driver.*\", pool=~\"PS.*\"}",
     "legendFormat": "{{pool}} ({{pod}})"
    }
   ]
  },
  {
   "title": "Driver JVM non-heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=~\"$namespace\", pod=~\".*driver.*\", area=\"nonheap\"}",
     "legendFormat": "Non-heap used ({{pod}})"
    },
    {
     "expr": "jvm_memory_bytes_committed{namespace=~\"$namespace\", pod=~\".*driver.*\", area=\"nonheap\"}",
     "legendFormat": "Non-heap committed ({{pod}})"
    }
   ]
  },
  {
   "title": "Driver process resident memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"$namespace\", pod=~\".*driver.*\"}",
     "legendFormat": "RSS ({{pod}})"
    }
   ]
  },
  { "title": "DAG Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "DAGScheduler message processing time (count)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_dagscheduler_messageprocessingtime_type_timers_count{app_namespace=~\"$namespace\"}",
     "legendFormat": "Message processing count ({{app_id}})"
    }
   ]
  },
  {
   "title": "LiveListenerBus (events / queue size)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_driver_livelistenerbus_numeventsposted_type_counters_count{app_namespace=~\"$namespace\"}",
     "legendFormat": "Events posted ({{app_id}})"
    },
    {
     "expr": "spark_driver_livelistenerbus_queue_appstatus_size_type_gauges{app_namespace=~\"$namespace\"}",
     "legendFormat": "AppStatus queue size ({{app_id}})"
    }
   ]
  }
 ]
}