{
 "title": "Spark Operator Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Spark_Operator_Instance",
    "label": "Spark Operator Instance",
    "query": "label_values(spark_application_submit_count{endpoint=\"metrics\"}, pod)"
   },
   {
    "name": "Spark_Metrics_Endpoint",
    "label": "Spark Metrics Endpoint",
    "query": "label_values(spark_application_submit_count, endpoint)"
   }
  ]
 },
 "panels": [
  { "title": "SparkApplication and Executors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Submitted SparkApplications",
   "type": "stat",
   "description": "Total number of SparkApplication submitted by the Operator.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_submit_count{endpoint=\"metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed SparkApplications",
   "type": "stat",
   "description": "Total number of SparkApplication which failed to complete.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_submit_count{endpoint=\"metrics\"}) - sum(spark_application_success_count{endpoint=\"metrics\"})"
    }
   ]
  },
  {
   "title": "Execution time for SparkApplications which succeeded.",
   "type": "graph",
   "description": "Execution time for applications which succeeded.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spark_application_success_execution_time_seconds_sum{endpoint=\"metrics\"}[5m])) / sum(rate(spark_application_success_execution_time_seconds_count{endpoint=\"metrics\"}[5m]))",
     "legendFormat": "Avg execution time"
    }
   ]
  },
  {
   "title": "Execution time for SparkApplications which failed.",
   "type": "graph",
   "description": "Execution time for applications which failed (not exposed by operator).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "spark_application_failure_execution_time_seconds_sum{endpoint=\"metrics\"}",
     "legendFormat": "quantile-{{quantile}}"
    }
   ]
  },
  {
   "title": "Running SparkApplications",
   "type": "stat",
   "description": "Total number of SparkApplication which are currently running.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_running_count{endpoint=\"metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed Spark Executors",
   "type": "stat",
   "description": "Total number of Spark Executors which failed.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_executor_failure_count{endpoint=\"metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Succ. completed SparkApplications.",
   "type": "stat",
   "description": "Total number of SparkApplication which completed successfully.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_application_success_count{endpoint=\"metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Running Spark Executors",
   "type": "stat",
   "description": "Total number of Spark Executors which are currently running.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_running_count{endpoint=\"metrics\"})"
    }
   ]
  },
  {
   "title": "Succ. Completed Spark Executors",
   "type": "stat",
   "description": "Total number of Spark Executors which completed successfully.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_success_count{endpoint=\"metrics\"})"
    }
   ]
  },
  { "title": "SparkApplication Work Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Adds handled by work queue",
   "type": "stat",
   "description": "Total number of adds handled by work queue",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workqueue_adds_total{controller=\"spark-application-controller\",name=\"spark-application-controller\",endpoint=\"metrics\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current depth of work queue",
   "type": "gauge",
   "description": "Current depth of work queue",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "workqueue_depth{controller=\"spark-application-controller\",name=\"spark-application-controller\",endpoint=\"metrics\"}"
    }
   ]
  },
  {
   "title": "Latency for work queue",
   "type": "graph",
   "description": "Latency for work queue",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_queue_duration_seconds_bucket{controller=\"spark-application-controller\",name=\"spark-application-controller\",endpoint=\"metrics\"}[5m])) by (le))",
     "legendFormat": "quantile-0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(workqueue_queue_duration_seconds_bucket{controller=\"spark-application-controller\",name=\"spark-application-controller\",endpoint=\"metrics\"}[5m])) by (le))",
     "legendFormat": "quantile-0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{controller=\"spark-application-controller\",name=\"spark-application-controller\",endpoint=\"metrics\"}[5m])) by (le))",
     "legendFormat": "quantile-0.99"
    }
   ]
  },
  {
   "title": "Processing an item from work queue duration",
   "type": "graph",
   "description": "How long processing an item from workqueue takes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_work_duration_seconds_bucket{controller=\"spark-application-controller\",name=\"spark-application-controller\",endpoint=\"metrics\"}[5m])) by (le))",
     "legendFormat": "quantile-0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(workqueue_work_duration_seconds_bucket{controller=\"spark-application-controller\",name=\"spark-application-controller\",endpoint=\"metrics\"}[5m])) by (le))",
     "legendFormat": "quantile-0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{controller=\"spark-application-controller\",name=\"spark-application-controller\",endpoint=\"metrics\"}[5m])) by (le))",
     "legendFormat": "quantile-0.99"
    }
   ]
  },
  {
   "title": "Retries handled by work queue",
   "type": "stat",
   "description": "Total number of retries handled by work queue",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workqueue_retries_total{controller=\"spark-application-controller\",name=\"spark-application-controller\",endpoint=\"metrics\"}"
    }
   ]
  },
  {
   "title": "Unfinished work",
   "type": "stat",
   "description": "Unfinished work in seconds",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workqueue_unfinished_work_seconds{controller=\"spark-application-controller\",name=\"spark-application-controller\",endpoint=\"metrics\"}"
    }
   ]
  },
  {
   "title": "Longest running processor",
   "type": "stat",
   "description": "Longest running processor in seconds",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "format": "none",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workqueue_longest_running_processor_seconds{controller=\"spark-application-controller\",name=\"spark-application-controller\",endpoint=\"metrics\"}"
    }
   ]
  },
  {
   "title": "ScheduledApplication Work Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Adds handled by work queue",
   "type": "stat",
   "description": "Total number of adds handled by workqueue",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
   "format": "none",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workqueue_adds_total{controller=\"scheduled-spark-application-controller\",name=\"scheduled-spark-application-controller\",endpoint=\"metrics\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current depth of work queue",
   "type": "gauge",
   "description": "Current depth of work queue",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "workqueue_depth{controller=\"scheduled-spark-application-controller\",name=\"scheduled-spark-application-controller\",endpoint=\"metrics\"}"
    }
   ]
  },
  {
   "title": "Latency for work queue",
   "type": "graph",
   "description": "Latency for work queue",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_queue_duration_seconds_bucket{controller=\"scheduled-spark-application-controller\",name=\"scheduled-spark-application-controller\",endpoint=\"metrics\"}[5m])) by (le))",
     "legendFormat": "quantile-0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(workqueue_queue_duration_seconds_bucket{controller=\"scheduled-spark-application-controller\",name=\"scheduled-spark-application-controller\",endpoint=\"metrics\"}[5m])) by (le))",
     "legendFormat": "quantile-0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{controller=\"scheduled-spark-application-controller\",name=\"scheduled-spark-application-controller\",endpoint=\"metrics\"}[5m])) by (le))",
     "legendFormat": "quantile-0.99"
    }
   ]
  },
  {
   "title": "Processing an item from work queue duration",
   "type": "graph",
   "description": "How long processing an item from workqueue takes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_work_duration_seconds_bucket{controller=\"scheduled-spark-application-controller\",name=\"scheduled-spark-application-controller\",endpoint=\"metrics\"}[5m])) by (le))",
     "legendFormat": "quantile-0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(workqueue_work_duration_seconds_bucket{controller=\"scheduled-spark-application-controller\",name=\"scheduled-spark-application-controller\",endpoint=\"metrics\"}[5m])) by (le))",
     "legendFormat": "quantile-0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{controller=\"scheduled-spark-application-controller\",name=\"scheduled-spark-application-controller\",endpoint=\"metrics\"}[5m])) by (le))",
     "legendFormat": "quantile-0.99"
    }
   ]
  },
  {
   "title": "Retries handled by work queue",
   "type": "stat",
   "description": "Total number of retries handled by work queue",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 21 },
   "format": "none",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workqueue_retries_total{controller=\"scheduled-spark-application-controller\",name=\"scheduled-spark-application-controller\",endpoint=\"metrics\"}"
    }
   ]
  },
  {
   "title": "Unfinished work",
   "type": "stat",
   "description": "Unfinished work in seconds",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "format": "none",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workqueue_unfinished_work_seconds{controller=\"scheduled-spark-application-controller\",name=\"scheduled-spark-application-controller\",endpoint=\"metrics\"}"
    }
   ]
  },
  {
   "title": "Longest running processor",
   "type": "stat",
   "description": "Longest running processor in seconds",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 23 },
   "format": "none",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workqueue_longest_running_processor_seconds{controller=\"scheduled-spark-application-controller\",name=\"scheduled-spark-application-controller\",endpoint=\"metrics\"}"
    }
   ]
  }
 ]
}